export const RECEIVE_CHATLIST = 'SERVER@@RECEIVE_CHATLIST';
export const RECEIVE_MESSAGE = 'SERVER@@RECEIVE_MESSAGE';
export const RECEIVE_STREAM = 'SERVER@@RECEIVE_STREAM';
export const SEND_MESSAGE = 'SERVER@@SEND_MESSAGE';

export const SELECT_CHAT = 'CHATS@@SELECT_CHAT';

export const INIT = '@INIT';
